base: _base.yaml

experiment:
  name: lstm

model:
  name: lstm
  sequence_mode: rows      # 32 steps, input_size = 3*32 = 96
  patch_size: 4
  hidden_size: 256
  num_layers: 2
  dropout: 0.2
  bidirectional: false
  head_dropout: 0.2

optim:
  lr: 0.001
  weight_decay: 0.0001
